# need secrets env vars
# 1. DOCKERHUB_USERNAME
# 2. DOCKERHUB_TOKEN see...(https://qiita.com/fudekun/items/0dad3f2251cca992d7d4)

name: Build container images
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: ["client", "server", "worker"]
        tag: ["client-k8s", "server-k8s-pgfix", "worker-k8s"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          BUILD_PATH: cygnetops
        with:
          context: ./${{ matrix.target }}
          push: true
          tags: cygnetops/multi-${{ matrix.tag }}:latest,cygnetops/multi-${{ matrix.tag }}:$GITHUB_SHA
