name: Release

on:
  push:
    branches:
      - master

jobs:
  job_id:
    # ...
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT_DEV }}
      PUSH_PATH: gcr.io/${{ secrets.GKE_PROJECT_DEV }}/cygnetops
      GKE_CLUSTER: multi-cluster
      GKE_ZONE: us-central1-c

    steps:
      # Install gcloud, do not specify authentication.
      - uses: "google-github-actions/setup-gcloud@master"
        with:
          project_id: ${{ secrets.GKE_PROJECT_DEV }}

      # Configure Workload Identity Federation and generate an access token.
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.1"
        with:
          create_credentials_file: "true"
          # `providers/gha-provider==PROVIDER_NAME` see (https://zenn.dev/vvakame/articles/gha-and-gcp-workload-identity)
          workload_identity_provider: "projects/967344766275/locations/global/workloadIdentityPools/github-actions/providers/gha-provider"
          service_account: "travis-deployer@multi-k8s-333119.iam.gserviceaccount.com"
          access_token_lifetime: 1200s

      # Authenticate using the created credentials file.
      #
      # WARNING: The --cred-file flag is in preview and is subject to change.
      - id: "gcloud"
        name: "gcloud"
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        run: |-

          # Now you can run gcloud commands authenticated as the impersonated service account.

          gcloud components update kubectl
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set project multi-k8s-333119
          gcloud config set compute/zone $GKE_ZONE
          gcloud container clusters get-credentials $GKE_CLUSTER

      # https://github.com/google-github-actions/get-gke-credentials
      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@v0.3.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build
        run: |-
          docker build -t $PUSH_PATH/multi-client-k8s:latest -t $PUSH_PATH/multi-client-k8s:$GITHUB_SHA -f ./client/Dockerfile ./client
          docker build -t $PUSH_PATH/multi-server-k8s-pgfix:latest -t $PUSH_PATH/multi-server-k8s-pgfix:$GITHUB_SHA -f ./server/Dockerfile ./server
          docker build -t $PUSH_PATH/multi-worker-k8s:latest -t $PUSH_PATH/multi-worker-k8s:$GITHUB_SHA -f ./worker/Dockerfile ./worker

      # Docker イメージを Google Container Registry にプッシュする
      - name: Publish
        run: |-
          docker push $PUSH_PATH/multi-client-k8s:latest
          docker push $PUSH_PATH/multi-server-k8s-pgfix:latest
          docker push $PUSH_PATH/multi-worker-k8s:latest

          docker push $PUSH_PATH/multi-client-k8s:$GITHUB_SHA
          docker push $PUSH_PATH/multi-server-k8s-pgfix:$GITHUB_SHA
          docker push $PUSH_PATH/multi-worker-k8s:$GITHUB_SHA

      # kustomize を設定する
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - id: deploy-pods
        name: Deploy
        run: |-
          ../kustomize build k8s | kubectl apply -f -
          kubectl set image deployments/server-deployment server=$PUSH_PATH/multi-server-k8s-pgfix:$GITHUB_SHA
          kubectl set image deployments/client-deployment client=$PUSH_PATH/multi-client-k8s:$GITHUB_SHA
          kubectl set image deployments/worker-deployment worker=$PUSH_PATH/multi-worker-k8s:$GITHUB_SHA
