# need secrets env vars
# 1. DOCKERHUB_USERNAME

name: DevClient
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build dev Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.dev
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-test

      - name: Test image
        run: |-
          docker run -e CI=true ${{ secrets.DOCKERHUB_USERNAME }}/react-test npm test
